services:
  mars-simulator:
    image: mars-iot-simulator:multiarch_v1
    container_name: mars-simulator
    ports:
      - "8081:8080" # Modified port in order to don't interfere with web-engine assignment
    networks:
      - mars-network

  # --- INFRASTRUTTURA: MESSAGE BROKER ---
  activemq-broker:
    image: apache/activemq-classic:latest
    container_name: activemq-broker
    healthcheck:
      # Usiamo nc per verificare che la porta JMS sia pronta
      test: ["CMD", "curl", "-f", "--user", "admin:admin", "http://localhost:8161/admin/"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    ports:
      - "61616:61616"
      - "5672:5672"
      - "8161:8161"
    networks:
      - mars-network
  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:8.17.0
  #   container_name: elasticsearch
  #   volumes:
  #     # Format: [HOST_PATH]:[CONTAINER_PATH]
  #     - ./history-service/logdata:/usr/share/elasticsearch/data
  #   environment:
  #     - discovery.type=single-node
  #     - xpack.security.enabled=false
  #     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #   ports:
  #     - "9200:9200"
  #   healthcheck:
  #     test: [ "CMD-SHELL", "curl -s http://localhost:9200/_cluster/health | grep -vq '\"status\":\"red\"'" ]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5
  #     start_period: 2s
  #   networks:
  #     - mars-network

  # kibana:
  #   image: docker.elastic.co/kibana/kibana:8.17.0
  #   container_name: kibana
  #   ports:
  #     - "5601:5601"
  #   environment:
  #     - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
  #   depends_on:
  #     elasticsearch:
  #       condition: service_healthy
  #   networks:
  #     - mars-network
  db-postgres-automation:
    image: postgres:15-alpine
    container_name: db-postgres-automation
    environment:
      POSTGRES_DB: myapp_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - ./automation-evaluator/postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d myapp_db" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - mars-network
      
  # --- MICROSERVIZI DI BACKEND ---
  sensors-ingestor:
    build:
      context: .
      dockerfile: ./sensors-ingestor/Dockerfile
    container_name: sensors-ingestor
    environment:
      - SPRING_ACTIVEMQ_BROKER_URL=tcp://activemq-broker:61616
      - SIMULATOR_URL=http://mars-simulator:8080
    depends_on:
      mars-simulator:
        condition: service_started
      activemq-broker:
        condition: service_healthy
      automation-evaluator:
        condition: service_started
    networks:
      - mars-network

  automation-evaluator:
    build:
      context: .
      dockerfile: ./automation-evaluator/Dockerfile
    container_name: automation-evaluator
    environment:
      - SPRING_ACTIVEMQ_BROKER_URL=tcp://activemq-broker:61616
    depends_on:
      db-postgres-automation:
        condition: service_healthy
      mars-simulator:
        condition: service_started
      activemq-broker:
        condition: service_healthy
    networks:
      - mars-network

  actuator-manager:
    build:
      context: .
      dockerfile: ./actuator-manager/Dockerfile
    container_name: actuator-manager
    environment:
      - SPRING_ACTIVEMQ_BROKER_URL=tcp://activemq-broker:61616
      - SIMULATOR_URL=http://mars-simulator:8080
    depends_on:
      mars-simulator:
        condition: service_started
      activemq-broker:
        condition: service_healthy
    networks:
      - mars-network

  # --- PRESENTATION LAYER (BFF + UI) ---
  web-engine:
    build:
      context: .
      dockerfile: ./web-engine/Dockerfile
    container_name: web-engine
    ports:
      - "8080:8080"
    environment:
      - SPRING_ACTIVEMQ_BROKER_URL=tcp://activemq-broker:61616
    depends_on:
      mars-simulator:
        condition: service_started
      activemq-broker:
        condition: service_healthy
    networks:
      - mars-network

networks:
  mars-network:
    driver: bridge