spring.application.name=web-engine
spring.jms.pub-sub-domain=true
spring.activemq.broker-url=tcp://activemq-broker:61616
spring.activemq.user=admin
spring.activemq.password=admin
spring.jms.listener.concurrency=1-5
spring.jms.listener.acknowledgment-mode=auto

# Logging
logging.level.root=INFO
logging.level.it.giallocarbonara=INFO
logging.level.org.springframework.jms=INFO
logging.level.org.springframework.web.socket=INFO