spring:
  application:
    name: history-service
  jms:
    # This is the crucial setting for Topics
    pub-sub-domain: true
  activemq:
    # Ensure this matches your docker-compose service name
    broker-url: tcp://activemq-broker:61616
    user: admin
    password: admin
    packages:
      trusted: "it.giallocarbonara, java.util, java.lang"

  threads:
    virtual:
      enabled: true  # Java 25 Power-up! ⚡

    elasticsearch:
      uris: http://elasticsearch:9200